/**
 * The parity suite: every committed golden replayed against the TypeScript port.
 *
 * The goldens are generated by `fixtures/generate/generate_goldens.py` against
 * the real Python reference modules and committed, so this suite runs in CI
 * with no Python, no reference checkout and no network. If a port drifts from
 * the doctrine it was ported from, a case fails here and names itself.
 *
 * Comparison is deep equality after rounding every number to six decimals.
 * Both runtimes use IEEE-754 doubles and both accumulate in the same order, so
 * the values agree far beyond six places; the rounding exists so that a
 * last-bit difference in a division never becomes a red build with no bug
 * behind it. Strings, including every rendered message, must match exactly.
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import { aggregateWeek, analyzeAccount, classifyTrend } from './analyze.js';
import { classifyCampaignCategory } from './classify.js';
import { crossCheck, renderVerdictEmojiLine, renderVerdictLine, type FigureSet } from './crosscheck.js';
import { evaluate, resolveGoalLens, type FlagsConfig } from './flags.js';
import { computePacing, pacingFlag, type PacingConfig, type SpendRow } from './pacing.js';
import {
  buildRecommendations,
  parseSignalDigestMarkdown,
  type RawEntity,
  type RawRadarRow,
  type RecConfig,
  type TestCandidate,
} from './recommendations.js';
import type { DailyRow } from './types.js';

const GOLDEN_DIR = fileURLToPath(new URL('../../../fixtures/golden/', import.meta.url));

interface GoldenFile<TCase> {
  schema: string;
  module: string;
  fixtures?: Record<string, SeriesFixture>;
  cases: TCase[];
}

interface SeriesFixture {
  account: string;
  reportDate: string;
  accountRows: DailyRow[];
  campaignRows: DailyRow[];
  metrics: string[] | null;
}

function loadGolden<TCase>(module: string): GoldenFile<TCase> {
  const file = JSON.parse(readFileSync(`${GOLDEN_DIR}${module}.json`, 'utf8')) as GoldenFile<TCase>;
  expect(file.schema).toBe('wizard-ads.parity.v1');
  expect(file.cases.length).toBeGreaterThan(0);
  return file;
}

/** Round every number in a structure to six decimals, leaving everything else alone. */
function round6(value: unknown): unknown {
  if (typeof value === 'number') {
    if (!Number.isFinite(value)) return value;
    return Number(value.toFixed(6));
  }
  if (Array.isArray(value)) return value.map(round6);
  if (value && typeof value === 'object') {
    const out: Record<string, unknown> = {};
    for (const [key, v] of Object.entries(value as Record<string, unknown>)) out[key] = round6(v);
    return out;
  }
  return value;
}

/**
 * Compare a port's output against a golden.
 *
 * `JSON.parse(JSON.stringify(...))` first, so `undefined` properties and the
 * absence of a property compare the same way the JSON golden represents them.
 */
function expectParity(actual: unknown, expected: unknown): void {
  expect(round6(JSON.parse(JSON.stringify(actual)))).toEqual(round6(expected));
}

function analysisFor(fixture: SeriesFixture) {
  return analyzeAccount(
    fixture.account,
    fixture.reportDate,
    fixture.accountRows,
    fixture.campaignRows,
    fixture.metrics ?? undefined,
  );
}

describe('parity: classify_campaign_category', () => {
  const golden = loadGolden<{ name: string; input: { campaignName: string }; expected: string }>('classify');
  for (const c of golden.cases) {
    it(c.name, () => {
      expect(classifyCampaignCategory(c.input.campaignName)).toBe(c.expected);
    });
  }
});

describe('parity: classify_trend', () => {
  const golden = loadGolden<{ name: string; input: { values: Array<number | null> }; expected: string }>('trend');
  for (const c of golden.cases) {
    it(c.name, () => {
      expect(classifyTrend(c.input.values)).toBe(c.expected);
    });
  }
});

describe('parity: analyze_account', () => {
  const golden = loadGolden<{ name: string; input: { fixture: string }; expected: unknown }>('analyze');
  for (const c of golden.cases) {
    it(c.name, () => {
      const fixture = golden.fixtures?.[c.input.fixture];
      expect(fixture, `missing fixture ${c.input.fixture}`).toBeDefined();
      expectParity(analysisFor(fixture as SeriesFixture), c.expected);
    });
  }
});

describe('parity: aggregate_week', () => {
  const golden = loadGolden<{
    name: string;
    input: { weekEnd: string; accountRows: DailyRow[] };
    expected: unknown;
  }>('weekly');
  for (const c of golden.cases) {
    it(c.name, () => {
      expectParity(aggregateWeek(c.input.accountRows, c.input.weekEnd), c.expected);
    });
  }
});

describe('parity: flags.evaluate', () => {
  const golden = loadGolden<{
    name: string;
    input: { fixture: string; config: FlagsConfig | null; goal: string | null };
    expected: { active: unknown[]; suppressed: unknown[] };
  }>('flags');
  for (const c of golden.cases) {
    it(c.name, () => {
      const fixture = golden.fixtures?.[c.input.fixture];
      expect(fixture, `missing fixture ${c.input.fixture}`).toBeDefined();
      const analysis = analysisFor(fixture as SeriesFixture);
      const result = evaluate(analysis, c.input.config, c.input.goal);
      expectParity({ active: result.active, suppressed: result.suppressed }, c.expected);
    });
  }

  it('every goal lens is exercised, including an unknown one', () => {
    const goals = new Set(golden.cases.map((c) => c.input.goal ?? 'none'));
    expect(goals.size).toBeGreaterThanOrEqual(9);
    expect(goals.has('not-a-real-goal')).toBe(true);
  });

  it('the suppressed-flag contract is covered by at least one case', () => {
    const suppressedCases = golden.cases.filter((c) => c.expected.suppressed.length > 0);
    expect(suppressedCases.length).toBeGreaterThan(0);
  });
});

describe('parity: pacing', () => {
  const golden = loadGolden<{
    name: string;
    input: {
      rows: SpendRow[];
      asOf: string;
      monthlyBudget: number | null;
      goal: string | null;
      config: PacingConfig | null;
    };
    expected: { pacing: unknown; flag: unknown };
  }>('pacing');
  for (const c of golden.cases) {
    it(c.name, () => {
      const lens = c.input.goal ? resolveGoalLens(c.input.goal) : null;
      const pacing = computePacing(c.input.rows, c.input.asOf, c.input.monthlyBudget, lens, c.input.config);
      expectParity({ pacing, flag: pacingFlag(pacing, lens) }, c.expected);
    });
  }
});

describe('parity: crosscheck', () => {
  const golden = loadGolden<{
    name: string;
    input: { sellerboard: FigureSet; adlabs: FigureSet; tolerance: number | null };
    expected: { result: unknown; line: string; emojiLine: string };
  }>('crosscheck');
  for (const c of golden.cases) {
    it(c.name, () => {
      const result =
        c.input.tolerance === null
          ? crossCheck(c.input.sellerboard, c.input.adlabs)
          : crossCheck(c.input.sellerboard, c.input.adlabs, c.input.tolerance);
      expectParity(
        { result, line: renderVerdictLine(result), emojiLine: renderVerdictEmojiLine(result) },
        c.expected,
      );
    });
  }
});

/** The golden serializes a parsed digest item in camelCase with sorted tag sets. */
interface GoldenSignalItem {
  hypothesis: string;
  successMetric: string;
  source: string;
  confidence: string;
  requires: string[][];
}

function toCandidate(item: GoldenSignalItem): TestCandidate {
  return {
    hypothesis: item.hypothesis,
    success_metric: item.successMetric,
    source: item.source,
    confidence: item.confidence,
    requires: item.requires,
  };
}

function toGoldenShape(candidate: TestCandidate): GoldenSignalItem {
  return {
    hypothesis: candidate.hypothesis,
    successMetric: candidate.success_metric as string,
    source: candidate.source as string,
    confidence: candidate.confidence as string,
    // Python sets are unordered, so the golden sorts each tag set.
    requires: (candidate.requires ?? []).map((tags) => [...tags].sort()),
  };
}

describe('parity: recommendations', () => {
  interface BuildCase {
    name: string;
    input: {
      rawEntities: RawEntity[];
      goal: string | null;
      situation: string | null;
      rankRadar: RawRadarRow[] | null;
      config: RecConfig | null;
      signalItems: GoldenSignalItem[] | null;
      pacing: { status: string; pace: number | null } | null;
    };
    expected: unknown;
  }
  interface DigestCase {
    name: string;
    input: { text: string };
    expected: GoldenSignalItem[];
  }
  const golden = loadGolden<BuildCase | DigestCase>('recommendations');

  for (const c of golden.cases) {
    if (c.name.startsWith('parse_signal_digest_markdown')) {
      const digest = c as DigestCase;
      it(digest.name, () => {
        const parsed = parseSignalDigestMarkdown(digest.input.text).map(toGoldenShape);
        expectParity(parsed, digest.expected);
      });
      continue;
    }
    const build = c as BuildCase;
    it(build.name, () => {
      const result = buildRecommendations(build.input.rawEntities, {
        goal: build.input.goal,
        situation: build.input.situation,
        rankRadar: build.input.rankRadar,
        config: build.input.config,
        signalItems: build.input.signalItems ? build.input.signalItems.map(toCandidate) : null,
        // Only `status` and `pace` are read; the golden carries the full result.
        pacing: build.input.pacing as never,
      });
      expectParity(result, build.expected);
    });
  }
});
